# Generated by Django 4.0.4 on 2022-05-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://boschbrandstore.com/wp-content/uploads/2019/01/no-image.png', max_length=355),
            preserve_default=False,
        ),
    ]
